-- =====================================================================
-- Ironbark iron ore plant monitoring: Unity Catalog DDL
-- =====================================================================
-- Read contract/naming.md first.
--
-- SECTION A is run by hand, once, in phase 0.
-- SECTION B is the agreed column contract for tables that Lakeflow
--           Declarative Pipelines creates and owns. DO NOT run it as DDL:
--           SDP must create its own streaming tables and materialized views,
--           and a hand-created table of the same name will conflict.
-- SECTION C is created by Lakebase CDF. DO NOT run it either.
--
-- All three lanes share ONE schema; see the ownership map in contract/naming.md.
-- =====================================================================


-- =====================================================================
-- SECTION A -- run this. Catalog, schemas, reference data, seed and
--              hand-owned output tables.
-- =====================================================================

-- The catalog and schema ALREADY EXIST and are not created here. Default Storage is
-- enabled on this account and the metastore has no storage root, so a new catalog
-- would land on Default Storage, which Lakebase CDF does not support.
-- jack_freeman_catalog has an external S3 root, so it is CDF-compatible.
--
-- Everything below goes into the one existing schema. See the table ownership map in
-- contract/naming.md: it is the only thing preventing three parallel sessions from
-- overwriting each other, now that there is no schema boundary to do it.

CREATE VOLUME IF NOT EXISTS jack_freeman_catalog.tech_summit_scada_build.landing
  COMMENT 'CSV seeds and file-based landing for the synthetic generator';

-- All three get the same working set. Differentiated grants (lane C read-only)
-- were in an earlier draft, but with one shared schema they give false comfort:
-- the table ownership map in contract/naming.md is the actual boundary, and
-- blocking someone mid-build costs more than the marginal protection buys.

GRANT USE CATALOG ON CATALOG jack_freeman_catalog TO `chris.dorrington@databricks.com`;
GRANT USE CATALOG ON CATALOG jack_freeman_catalog TO `jack.freeman@databricks.com`;
GRANT USE CATALOG ON CATALOG jack_freeman_catalog TO `adrian.tompkins@databricks.com`;

GRANT USE SCHEMA, SELECT, MODIFY, CREATE TABLE, CREATE VOLUME, CREATE FUNCTION, CREATE MODEL
  ON SCHEMA jack_freeman_catalog.tech_summit_scada_build TO `chris.dorrington@databricks.com`;
GRANT USE SCHEMA, SELECT, MODIFY, CREATE TABLE, CREATE VOLUME, CREATE FUNCTION, CREATE MODEL
  ON SCHEMA jack_freeman_catalog.tech_summit_scada_build TO `jack.freeman@databricks.com`;
GRANT USE SCHEMA, SELECT, MODIFY, CREATE TABLE, CREATE VOLUME, CREATE FUNCTION, CREATE MODEL
  ON SCHEMA jack_freeman_catalog.tech_summit_scada_build TO `adrian.tompkins@databricks.com`;

GRANT READ VOLUME, WRITE VOLUME ON VOLUME jack_freeman_catalog.tech_summit_scada_build.landing TO `chris.dorrington@databricks.com`;
GRANT READ VOLUME, WRITE VOLUME ON VOLUME jack_freeman_catalog.tech_summit_scada_build.landing TO `jack.freeman@databricks.com`;
GRANT READ VOLUME, WRITE VOLUME ON VOLUME jack_freeman_catalog.tech_summit_scada_build.landing TO `adrian.tompkins@databricks.com`;
GRANT USE SCHEMA, CREATE TABLE, CREATE VOLUME, CREATE FUNCTION, CREATE MODEL, SELECT, MODIFY
  ON SCHEMA jack_freeman_catalog.tech_summit_scada_build TO `<user_a>`;
GRANT USE SCHEMA, CREATE TABLE, CREATE VOLUME, CREATE FUNCTION, CREATE MODEL, SELECT, MODIFY
  ON SCHEMA jack_freeman_catalog.tech_summit_scada_build TO `<user_b>`;
-- Lane C reads only, plus WRITE VOLUME so the app can stage assets if it needs to.
GRANT USE SCHEMA, SELECT, CREATE TABLE ON SCHEMA jack_freeman_catalog.tech_summit_scada_build TO `<user_c>`;
GRANT READ VOLUME, WRITE VOLUME ON VOLUME jack_freeman_catalog.tech_summit_scada_build.landing TO `<user_a>`;
GRANT READ VOLUME ON VOLUME jack_freeman_catalog.tech_summit_scada_build.landing TO `<user_b>`;
GRANT READ VOLUME ON VOLUME jack_freeman_catalog.tech_summit_scada_build.landing TO `<user_c>`;


-- ---------------------------------------------------------------------
-- A.1  Reference data. Generated by contract/gen_reference_data.py.
-- ---------------------------------------------------------------------

-- The tag register. Single source of truth for the generator's operating
-- envelope, the rule engine's thresholds, and the app's tag metadata.
CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.dim_tag (
  tag_id           STRING  NOT NULL COMMENT 'e.g. CRU-PCR01-VI01',
  asset_id         STRING  NOT NULL COMMENT 'e.g. CRU-PCR01',
  asset_name       STRING  NOT NULL,
  asset_type       STRING  NOT NULL COMMENT 'crusher|screen|conveyor|bin|cyclone|stacker|feeder|thickener|sampler|utility',
  area_code        STRING  NOT NULL COMMENT 'ROM|CRU|SCR|DSD|STK|UTL|LAB',
  area_name        STRING  NOT NULL,
  measure          STRING  NOT NULL COMMENT 'mass_flow|vibration|temperature|...',
  instrument_type  STRING  NOT NULL COMMENT 'ISA-5.1-style code: WI|VI|TI|...',
  unit             STRING  NOT NULL,
  value_class      STRING  NOT NULL COMMENT 'analog|discrete',
  sample_hz        DOUBLE  NOT NULL COMMENT 'nominal sample rate; 10 Hz for vibration, 0.00056 for hourly lab',
  nominal          DOUBLE          COMMENT 'design operating point; generator centres here',
  lo_lo            DOUBLE          COMMENT 'trip limit, low',
  lo               DOUBLE          COMMENT 'warning limit, low',
  hi               DOUBLE          COMMENT 'warning limit, high',
  hi_hi            DOUBLE          COMMENT 'trip limit, high',
  is_mass_balance  BOOLEAN NOT NULL COMMENT 'feeds a flowsheet arc measurement',
  is_pdm           BOOLEAN NOT NULL COMMENT 'feeds the predictive maintenance feature set',
  enum_values      STRING          COMMENT 'pipe-delimited states for discrete tags',
  description      STRING,
  CONSTRAINT pk_dim_tag PRIMARY KEY (tag_id) RELY
) COMMENT 'Tag register. Regenerate via gen_reference_data.py, do not edit by hand.';

CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.dim_flowsheet_node (
  node_id             STRING  NOT NULL,
  node_name           STRING  NOT NULL,
  node_type           STRING  NOT NULL,
  area_code           STRING  NOT NULL,
  balance_role        STRING  NOT NULL COMMENT 'source|unit|sink. Only unit nodes are expected to close.',
  accumulation_tag_id STRING          COMMENT 'level tag, where the node holds inventory (bins, thickener)',
  capacity_t          DOUBLE          COMMENT 'live capacity in tonnes at 100% level; 0 where not applicable',
  layout_x            INT     NOT NULL COMMENT 'grid position for the app flowsheet',
  layout_y            INT     NOT NULL,
  CONSTRAINT pk_node PRIMARY KEY (node_id) RELY
) COMMENT 'Unit operations in the mass balance. The app draws from this, nothing is hardcoded in the UI.';

CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.dim_flowsheet_arc (
  arc_id         STRING  NOT NULL,
  from_node_id   STRING  NOT NULL,
  to_node_id     STRING  NOT NULL,
  arc_name       STRING  NOT NULL,
  design_tph     DOUBLE  NOT NULL COMMENT 'design basis tonnage, for deviation comparison',
  measure_tag_id STRING          COMMENT 'tag that measures this stream; NULL means inferred',
  measure_method STRING  NOT NULL COMMENT 'weightometer|slurry_flow_density|volume_flow|inferred',
  stream_type    STRING  NOT NULL COMMENT 'dry_solids|slurry|water',
  CONSTRAINT pk_arc PRIMARY KEY (arc_id) RELY,
  CONSTRAINT fk_arc_from FOREIGN KEY (from_node_id) REFERENCES jack_freeman_catalog.tech_summit_scada_build.dim_flowsheet_node,
  CONSTRAINT fk_arc_to   FOREIGN KEY (to_node_id)   REFERENCES jack_freeman_catalog.tech_summit_scada_build.dim_flowsheet_node
) COMMENT 'Material streams between nodes and the tag measuring each.';

CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.dim_rule (
  rule_id          STRING  NOT NULL,
  rule_name        STRING  NOT NULL,
  scope_type       STRING  NOT NULL COMMENT 'all|measure|asset_type|tag|node',
  scope_value      STRING          COMMENT 'the measure/asset_type/tag_id the rule applies to',
  rule_type        STRING  NOT NULL COMMENT 'limit_trip|limit_warn|rate_of_change|deviation|stale|imbalance|quality',
  severity         STRING  NOT NULL COMMENT 'CRITICAL|HIGH|WARNING|INFO',
  window_seconds   INT     NOT NULL COMMENT '0 for instantaneous rules',
  message_template STRING  NOT NULL COMMENT 'python format string over tag/asset/value fields',
  enabled          BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT pk_rule PRIMARY KEY (rule_id) RELY
)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')
COMMENT 'Alarm rules as data, so the streaming rule engine is a broadcast join rather than hardcoded predicates.';

-- Load the four CSVs. Upload them to the landing volume first. Note the explicit
-- casts: CSV columns arrive as STRING and will NOT merge into DOUBLE/INT/BOOLEAN
-- targets, and '' is loaded as NULL so the optional FK columns behave.
--   databricks fs cp contract/dim_tag.csv \
--     dbfs:/Volumes/jack_freeman_catalog/tech_summit_scada_build/landing/ref/dim_tag.csv --profile <profile>
COPY INTO jack_freeman_catalog.tech_summit_scada_build.dim_tag
  FROM (SELECT
          tag_id,
          asset_id,
          asset_name,
          asset_type,
          area_code,
          area_name,
          measure,
          instrument_type,
          unit,
          value_class,
          CAST(NULLIF(sample_hz, '') AS DOUBLE) AS sample_hz,
          CAST(NULLIF(nominal, '') AS DOUBLE) AS nominal,
          CAST(NULLIF(lo_lo, '') AS DOUBLE) AS lo_lo,
          CAST(NULLIF(lo, '') AS DOUBLE) AS lo,
          CAST(NULLIF(hi, '') AS DOUBLE) AS hi,
          CAST(NULLIF(hi_hi, '') AS DOUBLE) AS hi_hi,
          CAST(NULLIF(is_mass_balance, '') AS BOOLEAN) AS is_mass_balance,
          CAST(NULLIF(is_pdm, '') AS BOOLEAN) AS is_pdm,
          NULLIF(enum_values, '') AS enum_values,
          NULLIF(description, '') AS description
        FROM '/Volumes/jack_freeman_catalog/tech_summit_scada_build/landing/ref/dim_tag.csv')
  FILEFORMAT = CSV
  FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'false')
  COPY_OPTIONS ('force' = 'true');

COPY INTO jack_freeman_catalog.tech_summit_scada_build.dim_flowsheet_node
  FROM (SELECT
          node_id,
          node_name,
          node_type,
          area_code,
          balance_role,
          NULLIF(accumulation_tag_id, '') AS accumulation_tag_id,
          CAST(NULLIF(capacity_t, '') AS DOUBLE) AS capacity_t,
          CAST(NULLIF(layout_x, '') AS INT) AS layout_x,
          CAST(NULLIF(layout_y, '') AS INT) AS layout_y
        FROM '/Volumes/jack_freeman_catalog/tech_summit_scada_build/landing/ref/dim_flowsheet_node.csv')
  FILEFORMAT = CSV
  FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'false')
  COPY_OPTIONS ('force' = 'true');

COPY INTO jack_freeman_catalog.tech_summit_scada_build.dim_flowsheet_arc
  FROM (SELECT
          arc_id,
          from_node_id,
          to_node_id,
          arc_name,
          CAST(NULLIF(design_tph, '') AS DOUBLE) AS design_tph,
          NULLIF(measure_tag_id, '') AS measure_tag_id,
          measure_method,
          stream_type
        FROM '/Volumes/jack_freeman_catalog/tech_summit_scada_build/landing/ref/dim_flowsheet_arc.csv')
  FILEFORMAT = CSV
  FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'false')
  COPY_OPTIONS ('force' = 'true');

COPY INTO jack_freeman_catalog.tech_summit_scada_build.dim_rule
  FROM (SELECT
          rule_id,
          rule_name,
          scope_type,
          NULLIF(scope_value, '') AS scope_value,
          rule_type,
          severity,
          CAST(NULLIF(window_seconds, '') AS INT) AS window_seconds,
          message_template,
          CAST(NULLIF(enabled, '') AS BOOLEAN) AS enabled
        FROM '/Volumes/jack_freeman_catalog/tech_summit_scada_build/landing/ref/dim_rule.csv')
  FILEFORMAT = CSV
  FORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'false')
  COPY_OPTIONS ('force' = 'true');


-- ---------------------------------------------------------------------
-- A.2  The bronze reading contract, and the seed table that unblocks
--      lanes B and C before the live stream exists.
--
--      This shape is what the generator emits, what lands in Lakebase,
--      and what vw_tag_reading exposes. Agree it in phase 0 and freeze it:
--      it is the single dependency between all three lanes.
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.tag_reading_seed (
  event_id   STRING    NOT NULL COMMENT 'uuid4, idempotency key',
  tag_id     STRING    NOT NULL,
  source_ts  TIMESTAMP NOT NULL COMMENT 'when the instrument sampled',
  value      DOUBLE             COMMENT 'analog value; NULL for discrete tags',
  value_text STRING             COMMENT 'discrete state; NULL for analog tags',
  quality    STRING    NOT NULL COMMENT 'GOOD|BAD|UNCERTAIN|STALE',
  unit       STRING    NOT NULL COMMENT 'denormalised from dim_tag, as OPC-UA carries it',
  seq        BIGINT    NOT NULL COMMENT 'monotonic per tag, breaks ordering ties',
  producer   STRING    NOT NULL COMMENT 'generator instance id',
  ingest_ts  TIMESTAMP NOT NULL
)
CLUSTER BY (tag_id, source_ts)
COMMENT 'Static 24h synthetic sample. Lane A populates in phase 0 so lanes B and C are never blocked. Same shape as the live path.';

-- Long-horizon seed for model training. The 24h reading seed above cannot
-- train a predictive maintenance model, so lane A also generates 120 days of
-- 10-minute vibration features directly, including the injected failure events
-- described in contract/naming.md. Same columns as the SDP-managed
-- jack_freeman_catalog.tech_summit_scada_build.vibration_features_10m in section B.
CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.vibration_features_seed (
  asset_id                STRING    NOT NULL,
  tag_id                  STRING    NOT NULL,
  window_start            TIMESTAMP NOT NULL,
  window_end              TIMESTAMP NOT NULL,
  rms_mm_s                DOUBLE,
  peak_mm_s               DOUBLE,
  crest_factor            DOUBLE,
  kurtosis                DOUBLE,
  stddev_mm_s             DOUBLE,
  sample_count            BIGINT,
  rms_delta_1h            DOUBLE,
  rms_delta_24h           DOUBLE,
  rms_slope_24h           DOUBLE,
  rms_pct_of_baseline     DOUBLE,
  bearing_temp_c          DOUBLE,
  motor_current_a         DOUBLE,
  throughput_tph          DOUBLE,
  run_minutes             DOUBLE,
  hours_since_maintenance DOUBLE,
  iso_10816_zone          STRING    COMMENT 'A|B|C|D',
  label_failure_30d       BOOLEAN   COMMENT 'training label: window falls within 30 days of an injected failure'
)
CLUSTER BY (asset_id, window_start)
COMMENT '120 days of synthetic 10-minute vibration features with injected failures. Static, written once in phase 0.';

-- Lane B trains against this view, not the table, so the live features can be
-- unioned in later without changing the training or scoring code.
CREATE OR REPLACE VIEW jack_freeman_catalog.tech_summit_scada_build.vw_vibration_features AS
SELECT * FROM jack_freeman_catalog.tech_summit_scada_build.vibration_features_seed;
-- After seam 2, extend to:
--   SELECT * FROM jack_freeman_catalog.tech_summit_scada_build.vibration_features_seed
--   UNION ALL
--   SELECT * FROM jack_freeman_catalog.tech_summit_scada_build.vibration_features_10m;

-- ---------------------------------------------------------------------
-- A.3  THE SEAM. The only table lanes B and C read.
--      Phase 0 to seam 1: points at the seed table.
--      After seam 1: lane A swaps the body to the live path (see section C)
--      and nothing downstream changes.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW jack_freeman_catalog.tech_summit_scada_build.vw_tag_reading AS
SELECT event_id, tag_id, source_ts, value, value_text, quality, unit, seq, ingest_ts
FROM jack_freeman_catalog.tech_summit_scada_build.tag_reading_seed;

-- After seam 1, replace the body with the live Lakebase CDF path below.
--
-- IT MUST STAY A PLAIN FILTER. An earlier draft de-duplicated here with
-- ROW_NUMBER() OVER (PARTITION BY tag_id, seq ORDER BY _pg_lsn DESC), which
-- cannot be read by a streaming query: Structured Streaming does not support
-- non-time-based window functions on a streaming source. Lane B's _1m tables
-- are streaming reads of this view, so a window function here would break them
-- at seam 1 with no fix available from lane B's side.
--
-- De-duplication belongs in lane B's pipeline instead, where dropDuplicates
-- with a watermark on source_ts is supported. In practice duplicates only
-- arise if CDF re-snapshots a table, and event_id is unique per reading.
--
-- lb_tag_current_history is append-only, so it is a valid streaming source.
-- Each Postgres UPDATE lands as a preimage/postimage pair, hence the filter.
--
-- CREATE OR REPLACE VIEW jack_freeman_catalog.tech_summit_scada_build.vw_tag_reading AS
-- SELECT event_id, tag_id, source_ts, value, value_text, quality, unit, seq, ingest_ts
-- FROM jack_freeman_catalog.tech_summit_scada_build.lb_tag_current_history
-- WHERE _pg_change_type IN ('insert', 'update_postimage');


-- ---------------------------------------------------------------------
-- A.4  Hand-owned output tables. These are MERGE / INSERT targets rather
--      than SDP datasets, so they are created here.
-- ---------------------------------------------------------------------

-- Alerts. The foreach_batch_sink handler POSTs to the alerting endpoint and
-- records the outcome here, so a failed POST is visible rather than lost.
CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.alert (
  alert_id         STRING    NOT NULL,
  raised_at        TIMESTAMP NOT NULL,
  tag_id           STRING,
  asset_id         STRING,
  area_code        STRING,
  node_id          STRING             COMMENT 'set for imbalance rules, which are node-scoped',
  rule_id          STRING    NOT NULL,
  rule_name        STRING    NOT NULL,
  rule_type        STRING    NOT NULL,
  severity         STRING    NOT NULL COMMENT 'CRITICAL|HIGH|WARNING|INFO',
  trigger_value    DOUBLE,
  trigger_text     STRING,
  limit_low        DOUBLE,
  limit_high       DOUBLE,
  message          STRING    NOT NULL,
  delivery_status  STRING    NOT NULL COMMENT 'PENDING|DELIVERED|FAILED',
  delivery_attempts INT      NOT NULL DEFAULT 0,
  delivered_at     TIMESTAMP,
  http_status      INT,
  acknowledged_by  STRING,
  acknowledged_at  TIMESTAMP,
  CONSTRAINT pk_alert PRIMARY KEY (alert_id) RELY
)
CLUSTER BY (raised_at, severity)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')
COMMENT 'Rule failures. Written by the pipeline sink handler, acknowledged from the app.';

-- Stockpile state. Small, upserted, read live by the app.
CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.stockpile_state (
  stockpile_id        STRING    NOT NULL,
  as_at               TIMESTAMP NOT NULL,
  is_stacking         BOOLEAN   NOT NULL COMMENT 'from the STK-STK01-ZI02 stacking indicator',
  stacker_id          STRING,
  tonnes_stacked_cum  DOUBLE    NOT NULL COMMENT 'integrated from the stacker weightometer',
  tonnes_on_ground    DOUBLE    NOT NULL,
  avg_fe_pct          DOUBLE,
  avg_sio2_pct        DOUBLE,
  stack_started_at    TIMESTAMP,
  CONSTRAINT pk_stockpile PRIMARY KEY (stockpile_id) RELY
) COMMENT 'Current state per stockpile.';

-- Predictive maintenance scores. Written by both the batch scoring job and
-- the app's real-time calls to the serving endpoint, distinguished by scoring_mode.
CREATE OR REPLACE TABLE jack_freeman_catalog.tech_summit_scada_build.pdm_prediction (
  prediction_id       STRING    NOT NULL,
  asset_id            STRING    NOT NULL,
  tag_id              STRING             COMMENT 'the vibration tag scored, where scoring is per sensor',
  scored_at           TIMESTAMP NOT NULL,
  feature_window_end  TIMESTAMP NOT NULL COMMENT 'end of the feature window scored, for reproducibility',
  model_name          STRING    NOT NULL,
  model_version       STRING    NOT NULL,
  health_index        DOUBLE             COMMENT '0-100, 100 = healthy',
  failure_prob_30d    DOUBLE             COMMENT '0-1',
  predicted_rul_hours DOUBLE             COMMENT 'remaining useful life estimate',
  iso_10816_zone      STRING             COMMENT 'A|B|C|D vibration severity zone',
  top_features        STRING             COMMENT 'JSON array of {feature, contribution}',
  recommended_action  STRING,
  scoring_mode        STRING    NOT NULL COMMENT 'batch|realtime',
  CONSTRAINT pk_pdm_pred PRIMARY KEY (prediction_id) RELY
)
CLUSTER BY (asset_id, scored_at)
COMMENT 'Predictive maintenance scores. The AI layer reads this and can also call the endpoint directly.';


-- =====================================================================
-- SECTION B -- agreed column contract for SDP-managed datasets.
--              DO NOT RUN. Implement these in pipeline code; SDP creates
--              and owns the tables. Listed here so all three lanes agree
--              the columns before any of them are built.
--
-- Grain note: the _1m tables are tumbling-window aggregates over a
-- streaming source. Implement as streaming tables with a watermark
-- (windows are append-only once closed), not materialized views.
-- =====================================================================

-- jack_freeman_catalog.tech_summit_scada_build.tag_reading_1m   ST, watermark on source_ts, 1 min tumbling
--   tag_id STRING, window_start TIMESTAMP, window_end TIMESTAMP,
--   avg_value DOUBLE, min_value DOUBLE, max_value DOUBLE, stddev_value DOUBLE,
--   first_value DOUBLE, last_value DOUBLE,
--   sample_count BIGINT, good_count BIGINT, good_pct DOUBLE
--   CLUSTER BY (tag_id, window_start)

-- jack_freeman_catalog.tech_summit_scada_build.mass_flow_1m     one row per flowsheet arc per minute
--   arc_id STRING, window_start TIMESTAMP, window_end TIMESTAMP,
--   from_node_id STRING, to_node_id STRING, stream_type STRING,
--   measure_method STRING,
--   measured_tph DOUBLE,      -- weightometer avg, or Q * rho * Cw for slurry
--   design_tph DOUBLE, deviation_pct DOUBLE,
--   good_sample_pct DOUBLE,
--   is_estimated BOOLEAN      -- true where measure_tag_id IS NULL (inferred arcs)
--   CLUSTER BY (arc_id, window_start)

-- jack_freeman_catalog.tech_summit_scada_build.mass_balance_node_1m   THE flowsheet table the app renders
--   node_id STRING, window_start TIMESTAMP, window_end TIMESTAMP,
--   balance_role STRING,
--   mass_in_tph DOUBLE, mass_out_tph DOUBLE,
--   accumulation_tph DOUBLE,   -- d(inventory)/dt from level tag * capacity_t
--   imbalance_tph DOUBLE,      -- in - out - accumulation
--   imbalance_pct DOUBLE, closure_pct DOUBLE,
--   arcs_in_measured INT, arcs_in_total INT,
--   arcs_out_measured INT, arcs_out_total INT,
--   data_quality_pct DOUBLE,
--   status STRING              -- BALANCED|DRIFT|ALARM|INSUFFICIENT_DATA
--   CLUSTER BY (node_id, window_start)

-- jack_freeman_catalog.tech_summit_scada_build.equipment_state_1m
--   asset_id STRING, window_start TIMESTAMP, window_end TIMESTAMP,
--   state STRING, run_seconds INT, stop_seconds INT, fault_seconds INT,
--   availability_pct DOUBLE, avg_current_a DOUBLE, max_current_a DOUBLE,
--   starts INT, throughput_tph DOUBLE
--   CLUSTER BY (asset_id, window_start)

-- jack_freeman_catalog.tech_summit_scada_build.desands_balance_1m     single row per minute
--   window_start TIMESTAMP, window_end TIMESTAMP,
--   feed_slurry_m3h DOUBLE, feed_density_tm3 DOUBLE, feed_solids_tph DOUBLE,
--   overflow_slurry_m3h DOUBLE, overflow_density_tm3 DOUBLE, overflow_solids_tph DOUBLE,
--   underflow_slurry_m3h DOUBLE, underflow_density_tm3 DOUBLE, underflow_solids_tph DOUBLE,
--   water_added_m3h DOUBLE,
--   solids_recovery_pct DOUBLE, fines_reject_pct DOUBLE,
--   solids_imbalance_tph DOUBLE, water_imbalance_m3h DOUBLE

-- jack_freeman_catalog.tech_summit_scada_build.vibration_features_10m        the ML feature table
--   asset_id STRING, tag_id STRING, window_start TIMESTAMP, window_end TIMESTAMP,
--   rms_mm_s DOUBLE, peak_mm_s DOUBLE, crest_factor DOUBLE, kurtosis DOUBLE,
--   stddev_mm_s DOUBLE, sample_count BIGINT,
--   rms_delta_1h DOUBLE, rms_delta_24h DOUBLE, rms_slope_24h DOUBLE,
--   rms_pct_of_baseline DOUBLE,
--   bearing_temp_c DOUBLE, motor_current_a DOUBLE, throughput_tph DOUBLE,
--   run_minutes DOUBLE, hours_since_maintenance DOUBLE,
--   iso_10816_zone STRING,
--   label_failure_30d BOOLEAN   -- training label, from the generator's injected faults
--   CLUSTER BY (asset_id, window_start)


-- =====================================================================
-- SECTION C -- created by Lakebase Change Data Feed. DO NOT RUN.
--              Started once per schema, via the Lakebase UI or the Postgres
--              REST API / SDK (it IS scriptable). Requires a workspace admin
--              to have enabled the "Lakebase Change Data Feed" preview.
-- =====================================================================
--
-- jack_freeman_catalog.tech_summit_scada_build.lb_tag_current_history
--   all columns of the Lakebase `tag_current` table, plus CDC metadata:
--     _pg_change_type STRING     insert|update_preimage|update_postimage|delete
--     _pg_lsn         BIGINT     Postgres log sequence number, for ordering
--     _pg_xid         INT        transaction id
--     _timestamp      TIMESTAMP  when the sync processed the change
--     _sort_by        BIGINT     monotonic sort key
--
-- Batched and flushed roughly every 15 seconds, so this is the analytics
-- path's floor latency. The app's live tiles bypass it by reading Lakebase
-- directly.
--
-- Consumed through jack_freeman_catalog.tech_summit_scada_build.vw_tag_reading (see A.3), which filters
-- to insert + update_postimage. Do not read this table directly from lanes B or C.
--
-- Never enable Delta change data feed, a row filter, or a column mask on this
-- table. Any of the three permanently stops CDF writing to it.
--
-- jack_freeman_catalog.tech_summit_scada_build.lb_alert_outbox_history
--   will not exist until the first alert fires: CDF skips empty tables.
